/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public final class App {

    private App() {

    }

    public static void main(final String[] args) {
        Cli.greet();
    }
}
