/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.games.Games;

public final class App {

    private App() {

    }

    public static void main(final String[] args) {
        new Games().start(System.in);
    }
}
